### ISSUE TITLE
Will not work on a pi due to python 2.7 

### ISSUE THREAD

**Issue by altide8** [armageddon421/electrodacus-esp32#29]
I cant get platformio to run due to it saying python 3.6 is needed. I have 3.7 but it is defaulting to 2.7 for some reason. has anyone ran into this issue?

**Comment by armageddon421** [comment]
Please try the second answer to this:

https://stackoverflow.com/questions/62275714/how-to-change-the-default-python-version-in-raspberry-pi

**Comment by armageddon421** [comment]
It's been a month. Were you able to solve the issue?
