### ISSUE TITLE
s2 topic not being received

### ISSUE THREAD

**Issue by soggygeek** [armageddon421/electrodacus-esp32#33]
Maybe the s2 topic was never fully implemented.  I didn't know about it until someone else asked about it.  But I see in the code that you are monitoring for an s2 message from the Electrodacus and sending it on via MQTT.  However, I'm not receiving it.  Would love to be able to get the balancing info, either in the current /sbms topic or in a separate s2 topic.
My system is the latest version of SBMS0 with stock wifi module running version 0.3-dirty

**Comment by armageddon421** [comment]
the s2 topic should be there if you enabled it in the settings on the Data section. This may not yet be present in the firmware originally shipped by dacian. You need to use the latest master from this repo to have this feature. Closing this for now, please reopen if there are further questions.
