### ISSUE TITLE
Unpacked javascript sources available?

### ISSUE THREAD

**Issue by helgef** [armageddon421/electrodacus-esp32#36]
New user, thanks for the work put into this

I played around a bit with the code and implemented static IP addresses for my use. Thought I'd implement that in the UI as well as a setting on the config menu, but was unable to find the javascript source files in an unpacked manner anywhere in the project. Any chance you would release the unpacked javascript files (and perhaps add webpack to a build script?)

Happy to offer changes I make back as pull requests

**Comment by armageddon421** [comment]
https://github.com/armageddon421/electrodacus-dash
